-- Active: 1720880432598@@127.0.0.1@5433@postgres
CREATE DATABASE ChinguProjectDB;

CREATE TABLE users ( 
  id VARCHAR(255) PRIMARY KEY,
  user_email VARCHAR(255),
  name VARCHAR(30),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);