CREATE DATABASE v50_tier3_team_23;

CREATE TABLE users ( 
  id VARCHAR(255) PRIMARY KEY,
  user_email VARCHAR(255),
  name VARCHAR(30),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);